---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-web-service
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 3001
    nodePort: 31412
  selector:
    name: nodejs-web-app